### PR TITLE
Expand Readme to add contribution information

### PR DESCRIPTION
**Pull request by frenata**
Could do more to walk through people totally new to git/github, but I wanted to get the simplest viable contribution guide done.

### CODE REVIEW

**Comment by colonelpopcorn** [comment]
This is missing a section on setting up an upstream remote. If you don't have an upstream remote you won't be able to pull changes from the master repository. I'll see about setting this one up.

**Comment by frenata** [comment]
How detailed an explanation do we think we need? A link to an explanation, or step by step procedures?

**Comment by colonelpopcorn** [comment]
Not very detailed. Just make sure they know to get latest and merge or rebase before making a pull request. To set up a remote you just need to open your git repo in a command line and type:
`git remote add upstream https://github.com/WGUit/Flash.git`
 and then whenever a git pull or fetch is run it will pull and attempt to merge the latest.

**Comment by colonelpopcorn** [comment]
See OpenRA's strategy [here](https://github.com/OpenRA/OpenRA/wiki/Contributing#remotes)

**Review by colonelpopcorn — APPROVED** [review]
Good start.

**Pull request merged**
