### PR TITLE
Add deck class.

### PR DESCRIPTION
**Pull request by colonelpopcorn**
This class allows users to:

* Add cards to a deck
* Get certain cards from the deck by index (0-based)
* Shuffle the deck in memory or create a shuffled copy

This should close issue #12, but I'm honestly not sure what was meant by categorize. Did you want users to be able to categorize the cards in their deck individually, or does a deck count as a category? For example, you could have a deck of C176 cards or you could have a deck of Project Management cards with C179 and C176 cards in that particular deck.

### CODE REVIEW

**Comment by frenata** [comment]
I didn't originally write that use case, so I'm not certain how it was intended. Nor am I certain how flexible our 'category' model needs to be.

**Review by frenata — COMMENTED** [review]
The intended difference between `shuffleDeckByReference` and `shuffleDeckByValue` is just whether the list order is modified in place or not? I'm wondering whether both are necessary, or whether we can just pick one implementation and call it `shuffle`. 

On a similar note, I think `getCardByIndex` could be simplified to `get`. That would make it consistent with how other collections work, and such a renamed method is a great candidate for later overloading I think.

(Sorry if this seems nitpicky, I just figure this is likely to be a core API)

I have some broader thoughts on how this can be expanded to support some presumably common use cases, but I can do that myself.

Btw, thanks for including the great tests. :)

**Comment by colonelpopcorn** [comment]
Yeah, I'm good with simplifying the shuffle method, but I don't understand why we would want to simplify `getCardByIndex` to just `get`. When it's written that way it makes me think we are getting a Deck object and not a card object. I could meet you in the middle and just write it as `getCard`. What do you think?

**Edit:** BTW, which would you prefer an inline shuffle or a copy shuffle? I think a copy shuffle would be better because it leaves less room for side effects.

**Comment by frenata** [comment]
I guess I was thinking of it like a `pop` function, but in context, yeah, `getCard` is clearer.

Agreed that a copy shuffle is best.

**Review by frenata — APPROVED** [review]
Looks great!

**Pull request merged**
